apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    git-commit-hash: f9f5aa2e1e4d8c8868b3d9a69b484b9c75946912
  labels:
    app: kubed
  name: kubed-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: kubed
    spec:
      containers:
      - args:
        - run
        - --v=3
        - --api.address=:8080
        - --web.address=:56790
        image: appscode/kubed:0.3.0
        imagePullPolicy: IfNotPresent
        name: kubed
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP
        - containerPort: 56790
          name: web
          protocol: TCP
        volumeMounts:
        - mountPath: /srv/kubed
          name: config
        - mountPath: /tmp
          name: scratch
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - name: config
        secret:
          secretName: kubed-config
      - emptyDir: {}
        name: scratch
